package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;

import net.minecraft.block.Block;
import net.minecraft.block.BlockIce;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.entity.Entity;
import net.minecraft.util.IIcon;
import net.minecraft.world.World;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import java.lang.reflect.Field;
import java.util.Random;

public class EnchantedIce extends BlockIce {
    public IIcon baseIcon;

    public EnchantedIce() {
        super();
        this.setTickRandomly(false);
        this.setCreativeTab(LoECreativeTabs.tabBlockLoE);
        setBlockTextureName("minecraft:ice");
        setBlockName("lotr:enchantedIce");
        setLightLevel(0.25F);
    }

    @Override
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.baseIcon = iconRegister.registerIcon(this.getTextureName());
    }

    @Override
    public IIcon getIcon(int side, int meta) {
        return this.baseIcon;
    }

    public IIcon getBaseIcon() {
        return this.baseIcon;
    }

    @Override
    public void updateTick(World p_149674_1_, int p_149674_2_, int p_149674_3_, int p_149674_4_, Random p_149674_5_) {}
}
