package com.zivilon.cinder_loe.client.render;

import lotr.client.model.LOTRModelHuman;
import lotr.client.render.entity.LOTRRenderBiped;
import lotr.client.render.entity.LOTRRandomSkins;
import lotr.common.entity.LOTRRandomSkinEntity;
import lotr.common.entity.npc.LOTREntityNPC;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.util.ResourceLocation;

public class RenderUtumnoSlave extends LOTRRenderBiped {
    public static LOTRRandomSkins skins;

    public ModelBiped outfitModel = (ModelBiped)new LOTRModelHuman(0.6F, false);

    public RenderUtumnoSlave() {
        super((ModelBiped)new LOTRModelHuman(), 0.5F);
        setRenderPassModel((ModelBase)this.outfitModel);
        skins = LOTRRandomSkins.loadSkinsList("lotr:mob/scrapTrader");
    }

    public ResourceLocation getEntityTexture(Entity entity) {
        LOTREntityNPC lotrEntity = (LOTREntityNPC) entity;
        return skins.getRandomSkin(lotrEntity);
    }

    public int shouldRenderPass(EntityLiving entity, int pass, float f) {
        return super.shouldRenderPass(entity, pass, f);
    }
}
