package com.zivilon.cinder_loe.items;

import com.zivilon.cinder_loe.CinderLoE;
import com.zivilon.cinder_loe.LoECreativeTabs;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import lotr.common.LOTRBannerProtection;
import lotr.common.LOTRMod;
import lotr.common.enchant.LOTREnchantment;
import lotr.common.enchant.LOTREnchantmentHelper;
import lotr.common.item.LOTRItemSword;
import lotr.common.item.LOTRItemPolearm;
import lotr.common.item.LOTRMaterial;
import lotr.common.item.LOTRWeaponStats;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.EnumAction;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.util.DamageSource;
import net.minecraft.util.MathHelper;
import net.minecraft.util.MovingObjectPosition;
import net.minecraft.util.Vec3;
import net.minecraft.world.IBlockAccess;
import net.minecraft.world.World;

public class FirstAgeGlaive extends LOTRItemPolearm {
    public FirstAgeGlaive() {
        super(CinderLoE.MATERIAL_NEX_ICE);
        this.lotrWeaponDamage = 11.5F;
        this.setUnlocalizedName("lotr:firstAgeGlaive");
        this.setTextureName("lotr:firstAgeGlaive");
        this.setCreativeTab(LoECreativeTabs.tabCombatLoE);
        LOTRWeaponStats.registerMeleeReach(FirstAgeGlaive.class, 1.8F);
        LOTRWeaponStats.registerMeleeSpeed(FirstAgeGlaive.class, 1.0F);
    }

    public boolean getIsRepairable(ItemStack itemstack, ItemStack repairItem) {
        return (repairItem.getItem() == Item.getItemFromBlock(CinderLoE.enchantedIce));
    }

//    private void checkIncompatibleModifiers(ItemStack itemstack) {}

    public static UUID accessWeaponDamageModifier() {
        return null;
    }
}
