package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.Entity;
import net.minecraft.world.World;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

import com.zivilon.cinder_loe.util.Utilities;

import java.lang.reflect.Field;

public class RunedDwarvenBrick extends Block {

    public RunedDwarvenBrick() {
        super(Material.rock); // Choose the appropriate material
        setCreativeTab(LoECreativeTabs.tabDecoLoE);
        // Set other properties like hardness, resistance, name, etc.
        setHardness(2.0F);
        setResistance(5.0F);
        setBlockTextureName(Utilities.toSnakeCase("lotr:dwarven_brick_runed"));
        setBlockName("lotr:dwarvenBrickRuned");
       // setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:dwarven_brick_runed");
    }
}
