package com.zivilon.cinder_loe.client.render.corrupt;

import com.zivilon.cinder_loe.entity.corrupt.CorruptElf;
import com.zivilon.cinder_loe.entity.corrupt.CorruptMan;
import lotr.client.model.LOTRModelElf;
import lotr.client.model.LOTRModelHuman;
import lotr.client.render.entity.*;
import lotr.common.entity.LOTRRandomSkinEntity;
import lotr.common.entity.npc.LOTREntityMan;
import lotr.common.entity.npc.LOTREntityNPC;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.util.ResourceLocation;

public class RenderCorruptMan extends LOTRRenderGondorMan {
    public static LOTRRandomSkins skinsMale;
    public static LOTRRandomSkins skinsFemale;
    protected ModelBiped outfitModel = new LOTRModelHuman(0.6f, false);

    public RenderCorruptMan() {
        super();
        skinsMale = LOTRRandomSkins.loadSkinsList("cinder_loe:mob/corrupt/human_male");
        skinsFemale = LOTRRandomSkins.loadSkinsList("cinder_loe:mob/corrupt/human_female");
    }

    @Override
    public ResourceLocation getEntityTexture(Entity entity) {
        CorruptMan gondorian = (CorruptMan)entity;
        if (gondorian.familyInfo.isMale()) {
            return skinsMale.getRandomSkin(gondorian);
        }
        return skinsFemale.getRandomSkin(gondorian);
    }
    @Override
    public int shouldRenderPass(EntityLiving entity, int pass, float f) {
        CorruptMan dunedain = (CorruptMan)entity;
        return super.shouldRenderPass((EntityLiving)dunedain, pass, f);
    }
}
