package com.zivilon.cinder_loe.entity.corrupt;

import com.zivilon.cinder_loe.CinderLoE;
import com.zivilon.cinder_loe.CinderLoE_Config;
import lotr.common.LOTRFoods;
import lotr.common.LOTRMod;
import lotr.common.entity.ai.*;
import lotr.common.entity.npc.*;
import lotr.common.fac.LOTRFaction;
import lotr.common.quest.LOTRMiniQuest;
import lotr.common.quest.LOTRMiniQuestFactory;
import net.minecraft.entity.*;
import net.minecraft.entity.ai.*;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MovingObjectPosition;
import net.minecraft.util.StatCollector;
import net.minecraft.world.World;

public class CorruptMan extends LOTREntityGondorMan {

    public CorruptMan(World world) {
        super(world);
        ((EntityLiving) this).tasks.addTask(6, (EntityAIBase) new LOTREntityAIEat(this, LOTRFoods.ORC, 8000));
        ((EntityLiving) this).tasks.addTask(6, (EntityAIBase) new LOTREntityAIDrink(this, LOTRFoods.ORC_DRINK, 8000));
        this.addTargetTasks(true);
    }
    @Override
    public ItemStack getPickedResult(MovingObjectPosition target) {
        return null;
    }

    @Override
    public void setupNPCName() {
        this.familyInfo.setName(LOTRNames.getGondorName(this.rand, this.familyInfo.isMale()));
    }

    @Override
    public IEntityLivingData onSpawnWithEgg(IEntityLivingData data) {
        return null;
    }

    @Override
    public LOTRFaction getFaction() {
        return LOTRFaction.valueOf(CinderLoE_Config.corrupt_faction);
    }

    @Override
    public String getNPCName() {
        return this.familyInfo.getName();
    }
    @Override
    public float getAlignmentBonus() {
        return 0.0f;
    }

    @Override
    public boolean getCanSpawnHere() {
        return false;
    }

    @Override
    public float getBlockPathWeight(int i, int j, int k) {
        float f = 0.0f;
        return f;
    }
    @Override
    protected float getSoundPitch() {
        return super.getSoundPitch() * 0.65f;
    }
    @Override
    public String getHurtSound() {
        return "lotr:orc.hurt";
    }
    @Override
    public String getDeathSound() {
        return "lotr:orc.death";
    }

    @Override
    public String getAttackSound() {
        return "lotr:orc.attack";
    }
    @Override
    public String getSpeechBank(EntityPlayer entityplayer) {
        if (this.isFriendlyAndAligned(entityplayer)) {
            return "corruptSpeak/all/neutral";
        }
        return "corruptSpeak/all/hostile";
    }
    @Override
    public LOTRMiniQuest createMiniQuest() {
        return null;
    }

    @Override
    public LOTRMiniQuestFactory getBountyHelpSpeechDir() {
        return null;
    }

    @Override
    public void attackEntityWithRangedAttack(EntityLivingBase p_82196_1_, float p_82196_2_) {
    }
    @Override
    protected void dropFewItems(boolean flag, int i) {
        super.dropFewItems(flag, i);
    }
}
