package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import com.zivilon.cinder_loe.util.Utilities;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;

import java.lang.reflect.Field;

public class reeflessCoral extends Block {

    public reeflessCoral() {
        super(Material.rock); // Choose the appropriate material
        setCreativeTab(LoECreativeTabs.tabBlockLoE);
        // Set other properties like hardness, resistance, name, etc.
        setHardness(2.0F);
        setResistance(5.0F);
        setBlockTextureName(Utilities.toSnakeCase("lotr:reeflessCoral"));
        setBlockName("lotr:reeflessCoral");
       // setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:reeflessCoral");
    }

}
