package com.zivilon.cinder_loe.potion;

import net.minecraft.potion.Potion;
import net.minecraft.potion.PotionEffect;
import net.minecraft.entity.EntityLivingBase;

public class LoEPotions {
    public static Potion corrupting;
    public static Potion overdose;

    public static void registerPotions() {
        corrupting = new PotionCorrupting(31, false, 0x7F0000).setPotionName("potion.corrupting");
        overdose = new PotionHerbPoison(29, false, 0x114023).setPotionName("potion.overdose");
    }
}

