package com.zivilon.cinder_loe.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

import com.zivilon.cinder_loe.client.model.npc.ModelFangornWolf;

public class RenderFangornWolf extends RenderLiving {
    public static final ResourceLocation wolfSkin = new ResourceLocation("minecraft:textures/entity/wolf/wolf.png");
    
    public RenderFangornWolf() {
        super((ModelBase)new ModelFangornWolf(), 0.7F);
        setRenderPassModel((ModelBase)new ModelFangornWolf());
    }
    
    protected ResourceLocation getEntityTexture(Entity entity) {
        return wolfSkin;
    }
}
