package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import com.zivilon.cinder_loe.blocks.RotatableBlockBase3;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;

import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;

import java.lang.reflect.Field;

public class ReedBale extends RotatableBlockBase3 {
    public ReedBale() {
        super(Material.grass, "lotr:reedBale");
        setCreativeTab(LoECreativeTabs.tabDecoLoE);
        setStepSound(Block.soundTypeGrass);
        setBlockName("lotr:reedBale");
        setHardness(0.5F);
        setResistance(0.5F);
      //  setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }
}
