package com.zivilon.cinder_loe.client.model;// Made with Blockbench 4.12.4
// Exported for Minecraft version 1.7 - 1.12
// Paste this class into your mod and generate all required imports


import lotr.client.model.LOTRModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEsgarothHelmet extends LOTRModelBiped {
	private final ModelRenderer Hemlet;
	private final ModelRenderer FrontVisor;
	private final ModelRenderer bb_main2;
	private final ModelRenderer bb_main;
	private final ModelRenderer plumeee;
	private final ModelRenderer plume4_r1;
	private final ModelRenderer plume3_r1;
	private final ModelRenderer plume2_r1;
	private final ModelRenderer plume_r1;
	private final ModelRenderer plume5_r1;
	private final ModelRenderer cube_r1;

	public ModelEsgarothHelmet(float f) {
		super(f);
		textureWidth = 64;
		textureHeight = 64;

		Hemlet = new ModelRenderer(this);
		Hemlet.setRotationPoint(0.0F, 24.0F, 0.0F);

		FrontVisor = new ModelRenderer(this);
		FrontVisor.setRotationPoint(0.0F, 0.0F, 0.0F);
		FrontVisor.cubeList.add(new ModelBox(FrontVisor, 32, 6, -6.0F, -29.1F, -6.2F, 12, 1, 4, 0.0F));
		FrontVisor.cubeList.add(new ModelBox(FrontVisor, 14, 41, 0.0F, -35.0F, -6.0F, 0, 11, 12, 0.0F));

		bb_main2 = new ModelRenderer(this);
		bb_main2.setRotationPoint(0.0F, 0.0F, 0.0F);
		bb_main2.cubeList.add(new ModelBox(bb_main2, 0, 17, -3.5F, -33.2F, -5.5F, 7, 4, 11, 0.0F));

		bb_main = new ModelRenderer(this);
		bb_main.setRotationPoint(0.0F, 0.0F, 0.0F);
		bb_main.cubeList.add(new ModelBox(bb_main, 0, 0, -4.0F, -32.0F, -4.0F, 8, 8, 8, 1.0F));
		bb_main.cubeList.add(new ModelBox(bb_main, 0, 33, -5.5F, -28.0F, -6.0F, 11, 5, 12, 0.0F));

		plumeee = new ModelRenderer(this);
		plumeee.setRotationPoint(0.0F, 0.0F, 0.0F);

		plume4_r1 = new ModelRenderer(this);
		plume4_r1.setRotationPoint(0.0F, -35.0F, 0.0F);
		setRotationAngle(plume4_r1, -0.829F, 1.2217F, -1.309F);
		plume4_r1.cubeList.add(new ModelBox(plume4_r1, 44, 14, 0.0F, -9.0F, -3.0F, 0, 9, 6, 0.0F));

		plume3_r1 = new ModelRenderer(this);
		plume3_r1.setRotationPoint(0.0F, -35.0F, 0.0F);
		setRotationAngle(plume3_r1, -0.3054F, -0.829F, 0.829F);
		plume3_r1.cubeList.add(new ModelBox(plume3_r1, 44, 14, 0.0F, -9.0F, -3.0F, 0, 9, 6, 0.0F));

		plume2_r1 = new ModelRenderer(this);
		plume2_r1.setRotationPoint(0.0F, -35.0F, 0.0F);
		setRotationAngle(plume2_r1, -0.9163F, -1.0036F, 0.8727F);
		plume2_r1.cubeList.add(new ModelBox(plume2_r1, 44, 14, 0.0F, -9.0F, -3.0F, 0, 9, 6, 0.0F));

		plume_r1 = new ModelRenderer(this);
		plume_r1.setRotationPoint(0.0F, -35.0F, 0.0F);
		setRotationAngle(plume_r1, 0.0873F, 1.1345F, -0.6981F);
		plume_r1.cubeList.add(new ModelBox(plume_r1, 44, 14, 0.0F, -9.0F, -3.0F, 0, 9, 6, 0.0F));

		plume5_r1 = new ModelRenderer(this);
		plume5_r1.setRotationPoint(0.0F, -35.0F, 0.0F);
		setRotationAngle(plume5_r1, -0.5672F, -1.1781F, 0.3927F);
		plume5_r1.cubeList.add(new ModelBox(plume5_r1, 44, 14, 0.0F, -9.0F, -3.0F, 0, 9, 6, 0.0F));

		cube_r1 = new ModelRenderer(this);
		cube_r1.setRotationPoint(0.0F, -33.0F, 0.0F);
		setRotationAngle(cube_r1, 0.0F, -0.8727F, 0.0F);
		cube_r1.cubeList.add(new ModelBox(cube_r1, 0, 51, -1.0F, -2.0F, -1.0F, 2, 2, 2, 0.0F));

		this.bipedHead.cubeList.clear();

		bipedHead = new ModelRenderer(this);
		bipedHead.setRotationPoint(0.0F, 0.0F, 0.0F);
		bipedHead.cubeList.add(new ModelBox(bipedHead, 0, 0, -4.0F, -8.0F, -4.0F, 8, 8, 8, 1.0F));

		Hemlet.addChild(FrontVisor);
		Hemlet.addChild(bb_main2);
		Hemlet.addChild(bb_main);
		Hemlet.addChild(plumeee);
		plumeee.addChild(plume4_r1);
		plumeee.addChild(plume3_r1);
		plumeee.addChild(plume2_r1);
		plumeee.addChild(plume_r1);
		plumeee.addChild(plume5_r1);
		plumeee.addChild(cube_r1);

		this.bipedHead.addChild(this.Hemlet);

		this.bipedHeadwear.cubeList.clear();
		this.bipedBody.cubeList.clear();
		this.bipedRightArm.cubeList.clear();
		this.bipedLeftArm.cubeList.clear();
		this.bipedRightLeg.cubeList.clear();
		this.bipedLeftLeg.cubeList.clear();
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		bipedHead.render(f5);
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}