package com.zivilon.cinder_loe.client.model;

import lotr.client.model.LOTRModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class OrthancGuardHelmet extends LOTRModelBiped {
	private final ModelRenderer bb_main;
	private final ModelRenderer Topper;
	private final ModelRenderer Plume;
	private final ModelRenderer HelmetAddons;
	private final ModelRenderer RightGuard_r1;

	public OrthancGuardHelmet(float f) {
        super (f);
		textureWidth = 64;
		textureHeight = 64;

		bb_main = new ModelRenderer(this);
		bb_main.setRotationPoint(0.0F, 24.0F, 0.0F);
		bb_main.cubeList.add(new ModelBox(bb_main, 0, 0, -4.0F, -32.0F, -4.0F, 8, 8, 8, 1.0F));

		Topper = new ModelRenderer(this);
		Topper.setRotationPoint(0.0F, 0.0F, 0.0F);
		bb_main.addChild(Topper);
		Topper.cubeList.add(new ModelBox(Topper, 0, 58, -1.5F, -36.25F, -1.5F, 3, 2, 3, 0.1F));
		Topper.cubeList.add(new ModelBox(Topper, 0, 48, -3.5F, -34.0F, -3.5F, 7, 2, 7, 0.5F));

		Plume = new ModelRenderer(this);
		Plume.setRotationPoint(0.0F, 0.0F, 0.0F);
		bb_main.addChild(Plume);
		Plume.cubeList.add(new ModelBox(Plume, 31, 33, -8.0F, -40.9F, 0.25F, 16, 9, 0, 0.25F));
		Plume.cubeList.add(new ModelBox(Plume, 31, 52, -8.0F, -40.9F, -0.5F, 16, 9, 0, 0.25F));

		HelmetAddons = new ModelRenderer(this);
		HelmetAddons.setRotationPoint(0.0F, 0.0F, 0.0F);
		bb_main.addChild(HelmetAddons);
		HelmetAddons.cubeList.add(new ModelBox(HelmetAddons, -7, 32, -6.5F, -25.5F, 1.0F, 13, 0, 8, 0.0F));
		HelmetAddons.cubeList.add(new ModelBox(HelmetAddons, 36, 26, -5.0F, -28.8F, 4.3F, 10, 3, 1, 0.4F));
		HelmetAddons.cubeList.add(new ModelBox(HelmetAddons, 7, 17, 4.0F, -31.0F, -4.7F, 1, 5, 10, 0.4F));

		RightGuard_r1 = new ModelRenderer(this);
		RightGuard_r1.setRotationPoint(-4.0F, -28.46F, 0.8F);
		HelmetAddons.addChild(RightGuard_r1);
		setRotationAngle(RightGuard_r1, 0.0F, 1.5708F, 0.0F);
		RightGuard_r1.cubeList.add(new ModelBox(RightGuard_r1, 42, 9, -4.5F, -2.5F, -0.99F, 10, 5, 1, 0.4F));
        this.bipedHead.addChild(bb_main);

        this.bipedHead.cubeList.clear();
        this.bipedHeadwear.cubeList.clear();
        this.bipedBody.cubeList.clear();
        this.bipedRightArm.cubeList.clear();
        this.bipedLeftArm.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();

	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		this.bipedHead.render(f5);
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}
