package com.zivilon.cinder_loe.client.model;

import lotr.client.model.LOTRModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

// Made with Blockbench 4.12.5
// Exported for Minecraft version 1.7 - 1.12
// Paste this class into your mod and generate all required imports

public class ModelHelmetSunlitWarden extends LOTRModelBiped {
    public ModelRenderer bb_main;
    public ModelRenderer Crest_r1;
    public ModelRenderer PlumeHolder_r1;
    public ModelRenderer PlumeTopper_r1;

    public ModelHelmetSunlitWarden(float f) {
        super(f);
        textureWidth = 64;
        textureHeight = 64;

		bb_main = new ModelRenderer(this);
		bb_main.setRotationPoint(0.0F, 24.0F, 0.0F);
		bb_main.cubeList.add(new ModelBox(bb_main, 32, 15, -4.0F, -32.0F, -4.0F, 8, 8, 8, 1.0F));
		bb_main.cubeList.add(new ModelBox(bb_main, 18, 43, -6.0F, -30.3F, -6.0F, 12, 1, 4, 0.0F));
		bb_main.cubeList.add(new ModelBox(bb_main, 44, 0, -1.0F, -33.1F, -5.1F, 2, 4, 8, 0.0F));

		Crest_r1 = new ModelRenderer(this);
		Crest_r1.setRotationPoint(-1.0F, -30.0F, -7.0F);
		bb_main.addChild(Crest_r1);
		setRotationAngle(Crest_r1, -0.3491F, 0.0F, 0.0F);
		Crest_r1.cubeList.add(new ModelBox(Crest_r1, 0, 24, 1.0F, -15.5F, -1.25F, 0, 16, 24, 0.0F));

		PlumeHolder_r1 = new ModelRenderer(this);
		PlumeHolder_r1.setRotationPoint(0.0F, -33.5F, 1.0F);
		bb_main.addChild(PlumeHolder_r1);
		setRotationAngle(PlumeHolder_r1, -0.2182F, 0.0F, 0.0F);
		PlumeHolder_r1.cubeList.add(new ModelBox(PlumeHolder_r1, 0, 32, -1.0F, -1.0F, -1.0F, 2, 2, 4, 0.0F));

		PlumeTopper_r1 = new ModelRenderer(this);
		PlumeTopper_r1.setRotationPoint(-3.0F, -35.5F, -0.5F);
		bb_main.addChild(PlumeTopper_r1);
		setRotationAngle(PlumeTopper_r1, -0.3491F, 0.0F, 0.0F);
		PlumeTopper_r1.cubeList.add(new ModelBox(PlumeTopper_r1, 40, 31, 1.5F, -1.0F, -1.5F, 3, 2, 9, 0.0F));

        this.bipedHeadwear.cubeList.clear();
        this.bipedBody.cubeList.clear();
        this.bipedRightArm.cubeList.clear();
        this.bipedLeftArm.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();

        this.bipedHead.addChild(this.bb_main);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        bipedHead.render(f5);
    }

    public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
