package com.zivilon.cinder_loe.client.render;

import lotr.client.model.LOTRModelBoar;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class RenderFangornWildBoar extends RenderLiving {
    public static ResourceLocation boarSkin = new ResourceLocation("lotr:mob/boar/boar.png");
    
    public RenderFangornWildBoar() {
        super((ModelBase)new LOTRModelBoar(), 0.7F);
        setRenderPassModel((ModelBase)new LOTRModelBoar(0.5F));
    }
    
    protected ResourceLocation getEntityTexture(Entity entity) {
        return boarSkin;
    }
}
