package com.zivilon.cinder_loe.client.render;

import lotr.client.render.entity.LOTRRandomSkins;
import lotr.common.entity.LOTRRandomSkinEntity;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

import com.zivilon.cinder_loe.client.model.npc.ModelFangornAuroch;
import com.zivilon.cinder_loe.entity.npc.radagast.FangornAuroch;

public class RenderFangornAuroch extends RenderLiving {
  public static LOTRRandomSkins aurochsSkins;
  
  public RenderFangornAuroch() {
    super((ModelBase)new ModelFangornAuroch(), 0.5F);
    aurochsSkins = LOTRRandomSkins.loadSkinsList("lotr:mob/aurochs");
  }
  
  public ResourceLocation getEntityTexture(Entity entity) {
    FangornAuroch aurochs = (FangornAuroch)entity;
    ResourceLocation skin = aurochsSkins.getRandomSkin((LOTRRandomSkinEntity)aurochs);
    return skin;
  }
}