package com.zivilon.cinder_loe.blocks;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.util.IIcon;

import java.lang.reflect.Field;

public class FishBarrel extends StaticBlockBase3 {

    public FishBarrel() {
        super(Material.wood, "lotr:fishbarrel");
        try {
            Field tabField = LOTRCreativeTabs.class.getDeclaredField("tabDeco"); // Stupid workaround because ForgeGradle tries to obfuscate field LOTRCreativeTabs.tabBlock when it's not supposed to
            LOTRCreativeTabs tab = (LOTRCreativeTabs)tabField.get(null);
            setCreativeTab((CreativeTabs)tab);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
        setStepSound(Block.soundTypeWood);
        setBlockName("lotr:fishbarrel");
        setHardness(1.0F);
        setResistance(2.0F);
      //  setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }
}
