package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.blocks.RotatableBlockBase3;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;

import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;

import java.lang.reflect.Field;

public class LeatherBundle extends RotatableBlockBase3 {
    public LeatherBundle() {
        super(Material.cloth, "lotr:leatherBundle");
        try {
            Field tabField = LOTRCreativeTabs.class.getDeclaredField("tabDeco"); // Stupid workaround because ForgeGradle tries to obfuscate field LOTRCreativeTabs.tabBlock when it's not supposed to
            LOTRCreativeTabs tab = (LOTRCreativeTabs)tabField.get(null);
            setCreativeTab((CreativeTabs)tab);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
        setStepSound(Block.soundTypeCloth);
        setBlockName("lotr:leatherBundle");
        setHardness(0.5F);
        setResistance(0.5F);
      //  setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }
}
