package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.util.Utilities;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;

public class voidblock extends Block {

    public voidblock() {
        super(Material.rock); // Choose the appropriate material
        // Set other properties like hardness, resistance, name, etc.
        setHardness(100.0F);
        setResistance(100.0F);
        setBlockTextureName(Utilities.toSnakeCase("lotr:voidblock"));
        setBlockName("lotr:voidblock");
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:voidblock");
    }

}
