package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import com.zivilon.cinder_loe.util.Utilities;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;

import java.lang.reflect.Field;

public class cutDrystone extends Block {

    public cutDrystone() {
        super(Material.rock); // Choose the appropriate material
        // Set other properties like hardness, resistance, name, etc.
        this.setCreativeTab(LoECreativeTabs.tabBlockLoE);
        setHardness(2.0F);
        setResistance(5.0F);
        setBlockTextureName(Utilities.toSnakeCase("lotr:cut_drystone"));
        setBlockName("lotr:cutDrystone");
     //   setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabBlock);
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:cutDrystone");
    }

}
