package com.zivilon.cinder_loe.entity.npc.dwarf;

import com.zivilon.cinder_loe.CinderLoE;

import lotr.common.item.LOTRItemBanner;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.item.ItemStack;
import net.minecraft.world.World;
import lotr.common.entity.npc.LOTRBannerBearer;
import net.minecraft.util.MovingObjectPosition;


public class RedDwarfBannerBearer extends RedDwarfWarrior implements LOTRBannerBearer {
    public RedDwarfBannerBearer(World world) {
        super(world);
    }
      
    public LOTRItemBanner.BannerType getBannerType() {
        return LOTRItemBanner.BannerType.forID(42);
    }
    @Override
    public ItemStack getPickedResult(MovingObjectPosition target) {
        return new ItemStack(CinderLoE.spawnEgg, 1, 12);
    }

    @Override
    public void attackEntityWithRangedAttack(EntityLivingBase p_82196_1_, float p_82196_2_) {
    }

}
