package com.zivilon.cinder_loe.client.render;

import lotr.client.model.LOTRModelBoar;
import lotr.client.model.LOTRModelCrocodile;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class RenderTamedCrocodile extends RenderLiving {
    public static ResourceLocation crocskin = new ResourceLocation("lotr:mob/crocodile.png");

    public RenderTamedCrocodile() {
        super((ModelBase)new LOTRModelCrocodile(), 0.7F);
        setRenderPassModel((ModelBase)new LOTRModelCrocodile());
    }
    
    protected ResourceLocation getEntityTexture(Entity entity) {
        return crocskin;
    }
}
