package com.zivilon.cinder_loe.items;

import lotr.common.item.LOTRMaterial;
import lotr.common.item.LOTRItemBow;
import com.zivilon.cinder_loe.LoECreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class LoEBow extends LOTRItemBow {
    public Item repair_item;

    public LoEBow(LOTRMaterial material) {
        this(material, (Item) null, 1.0D);
    }
    public LoEBow(LOTRMaterial material, Block repair_block) {
        this(material, Item.getItemFromBlock(repair_block), 1.0D);
    }
    public LoEBow(LOTRMaterial material, Block repair_block, double damage) {
        this(material, Item.getItemFromBlock(repair_block), damage);
    }
    public LoEBow(LOTRMaterial material, double damage, Block repair_block) {
        this(material, Item.getItemFromBlock(repair_block), damage);
    }
    public LoEBow(LOTRMaterial material, double damage) {
        this(material, (Item) null, damage);
    }
    public LoEBow(LOTRMaterial material, double damage, Item item) {
        this(material, item, damage);
    }
    public LoEBow(LOTRMaterial material, Item item, double damage) {
        super(material, damage);
        repair_item = item;
        setCreativeTab(LoECreativeTabs.tabCombatLoE);
    }

    @Override
    public boolean getIsRepairable(ItemStack item, ItemStack repair_material) {
        if (repair_material.getItem() == repair_item)
            return true;
        return false;
    }
}
