package com.zivilon.cinder_loe;

import com.zivilon.cinder_loe.CinderLoE;
import lotr.common.item.LOTRItemFood;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraft.item.crafting.IRecipe;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.OreDictionary;
import net.minecraftforge.oredict.ShapedOreRecipe;
import lotr.common.LOTRMod;
import lotr.common.recipe.LOTRRecipes;
import lotr.common.recipe.LOTRRecipePoisonWeapon;
import net.minecraftforge.oredict.ShapelessOreRecipe;

public class recipes {

    public static void registerRecipes() {
        // Register a block recipe
        System.out.println("[CinderLoE] Registering recipes...");
        registerGeneralRecipes();
        registerRedDwarvenRecipes();
        registerLimwaithRecipes();
        registerBreeRecipes();
        registerArnorRecipes();
    }


    public static void registerGeneralRecipes() {
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.bowAsh), new Object[] { " XS", "X S", " XS",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('S'), Items.string }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.spearAsh), new Object[] { "  X", " Y ", "Y  ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.swordAsh), new Object[] { " X ", " X ", " Y ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.staffAsh), new Object[] { " XX", " YX", "Y  ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.battleaxeAsh), new Object[] { "XXX", "XYX", " Y ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.pikeAsh), new Object[] { "  X", " YX", "Y  ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.hammerAsh), new Object[] { "XYX", "XYX", " Y ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.daggerAsh), new Object[] { "X ", "Y ",
                Character.valueOf('X'), CinderLoE.ingotAsh, Character.valueOf('Y'), "stickWood" }));

        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.spicedHam), CinderLoE.spice, Items.cooked_porkchop));

        OreDictionary.registerOre("vegetable1", CinderLoE.onion);
        OreDictionary.registerOre("vegetable1", LOTRMod.leek);
        OreDictionary.registerOre("vegetable2", CinderLoE.cabbage);
        OreDictionary.registerOre("vegetable2", LOTRMod.lettuce);
        OreDictionary.registerOre("vegetable3", Items.carrot);
        OreDictionary.registerOre("vegetable3", Items.potato);
        OreDictionary.registerOre("vegetable3", LOTRMod.turnip);

        OreDictionary.registerOre("fruit1", Items.apple);
        OreDictionary.registerOre("fruit1", LOTRMod.pear);
        OreDictionary.registerOre("fruit1", LOTRMod.appleGreen);
        OreDictionary.registerOre("fruit1", LOTRMod.mango);
        OreDictionary.registerOre("fruit1", LOTRMod.orange);
        OreDictionary.registerOre("fruit2", LOTRMod.cherry);
        OreDictionary.registerOre("fruit2", Items.melon);
        OreDictionary.registerOre("fruit2", LOTRMod.banana);
        OreDictionary.registerOre("fruit2", LOTRMod.pomegranate);
        OreDictionary.registerOre("fruit3", LOTRMod.blueberry);
        OreDictionary.registerOre("fruit3", LOTRMod.raspberry);
        OreDictionary.registerOre("fruit3", LOTRMod.cranberry);
        OreDictionary.registerOre("fruit3", LOTRMod.blackberry);
        OreDictionary.registerOre("fruit3", LOTRMod.grapeRed);
        OreDictionary.registerOre("fruit3", LOTRMod.grapeWhite);

        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.lightStew), Items.bowl, "vegetable1", "vegetable2", "vegetable3"));

        OreDictionary.registerOre("meat", Items.cooked_beef);
        OreDictionary.registerOre("meat", Items.cooked_chicken);
        OreDictionary.registerOre("meat", Items.cooked_porkchop);
        OreDictionary.registerOre("meat", LOTRMod.camelCooked);
        OreDictionary.registerOre("meat", LOTRMod.deerCooked);
        OreDictionary.registerOre("meat", LOTRMod.muttonCooked);
        OreDictionary.registerOre("meat", LOTRMod.lionCooked);
        OreDictionary.registerOre("meat", LOTRMod.rhinoCooked);
        OreDictionary.registerOre("meat", LOTRMod.rabbitCooked);
        OreDictionary.registerOre("meat", LOTRMod.zebraCooked);

        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.fruitsalad), Items.bowl, "fruit1", "fruit2", "fruit3"));
        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.pasta, 4), LOTRMod.rollingPin, CinderLoE.dough, CinderLoE.dough));
        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.halva), Items.sugar, CinderLoE.dough, CinderLoE.spice, LOTRMod.almond));
        //takes durability from rolling pin
        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.chocolatebar, 2), LOTRMod.mugChocolate));

        GameRegistry.addRecipe(new ShapelessOreRecipe(new ItemStack(CinderLoE.pelmen), Items.wheat, "meat", LOTRMod.salt));

        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.cinderBlock), new Object[] { "XXX", "XYX", "XXX",
            Character.valueOf('X'), Blocks.stone, Character.valueOf('Y'), LOTRMod.balrogFire }));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.reedBale), new Object[] { "XXX", "XXX", "XXX",
            Character.valueOf('X'), LOTRMod.reeds}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.leatherBundle), new Object[] { "XXX", "XXX", "XXX",
            Character.valueOf('X'), Items.leather}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.pretzel, 2), new Object[] { "XYX", " X ",
                Character.valueOf('X'), CinderLoE.dough, Character.valueOf('Y'), LOTRMod.salt}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.dough, 8), new Object[] { "XXX", "XYX", "XXX",
            Character.valueOf('X'), CinderLoE.flour, Character.valueOf('Y'), Items.water_bucket}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.fishBarrel), new Object[] { "XXX", "XXX", "XXX",
            Character.valueOf('X'), Items.fish}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.rustedsword, 8), new Object[] { "X", "y", "y",
        Character.valueOf('Y'), Items.iron_ingot, Character.valueOf('X'), "stickWood"}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.silverChain, 8), new Object[] { "X", "X", "X",
            Character.valueOf('X'), LOTRMod.silver}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.goldChain, 8), new Object[] { "X", "X", "X",
            Character.valueOf('X'), Items.gold_ingot}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.ironChain, 8), new Object[] { "X", "X", "X",
            Character.valueOf('X'), Items.iron_ingot}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.bronzeChain, 8), new Object[] { "X", "X", "X",
                Character.valueOf('X'), LOTRMod.bronze}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.cobbleDrystone, 4), new Object[] { "XX", "XX",
                Character.valueOf('X'), LOTRMod.cobblebrick}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.cutDrystone, 4), new Object[] { "XX", "XX",
                Character.valueOf('X'), CinderLoE.cobbleDrystone}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(LOTRMod.cobblebrick, 4), new Object[] { "XX", "XX",
                Character.valueOf('X'), CinderLoE.cutDrystone}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.reeflessCoral, 1), new Object[] { "X",
                Character.valueOf('X'), LOTRMod.coralReef}));
        GameRegistry.addRecipe((IRecipe)new ShapedOreRecipe(new ItemStack(CinderLoE.plaster, 4), new Object[] { "XYX", "YXY", "XYX",
                Character.valueOf('X'), Items.paper, Character.valueOf('Y'), Blocks.clay }));

    }
    public static void registerRedDwarvenRecipes() {
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetRedDwarf), new Object[] { "XXX", "X X",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bodyRedDwarf), new Object[] { "X X", "XXX", "XXX",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.legsRedDwarf), new Object[] { "XXX", "X X", "X X",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bootsRedDwarf), new Object[] { "X X", "X X",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.spearRedDwarf), new Object[] { "  X", " Y ", "Y  ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.swordRedDwarf), new Object[] { " X ", " X ", " Y ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.battleaxeRedDwarf), new Object[] { "XXX", "XYX", " Y ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.pikeRedDwarf), new Object[] { "  X", " YX", "Y  ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.hammerRedDwarf), new Object[] { "XYX", "XYX", " Y ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.daggerRedDwarf), new Object[] { "X ", "Y ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.crossbowRedDwarf), new Object[] { "XXY", "ZYX", "YZX",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "stickWood", Character.valueOf('Z'), "string" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.boarArmorRedDwarf), new Object[] { "X  ", "XYX", "XXX",
            Character.valueOf('X'), CinderLoE.redDwarfSteel, Character.valueOf('Y'), "leather" }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.blockRedDwarfSteel), new Object[] { "XXX", "XXX", "XXX",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.redDwarfSteel), new Object[] { "X ", "  ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.chandelierRedDwarf, 2), new Object[] { " X ", "ZYZ", "   ",
            Character.valueOf('X'), "stickWood", Character.valueOf('Y'), CinderLoE.redDwarfSteel, Character.valueOf('Z'), Blocks.torch }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.barsRedDwarf, 16), new Object[] { "XXX", "XXX", "   ",
            Character.valueOf('X'), CinderLoE.redDwarfSteel }));
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.dwarvenBrickRuned, 4), new Object[] { " X ", "XYX", " X ",
            Character.valueOf('X'), new ItemStack(LOTRMod.brick, 1, 6), Character.valueOf('Y'), Items.gold_nugget}));
        GameRegistry.addShapelessRecipe(new ItemStack(CinderLoE.redDwarfSteel, 9), new Object[] { new ItemStack(CinderLoE.blockRedDwarfSteel) });
        GameRegistry.addRecipe(new ItemStack(CinderLoE.blockRedDwarfSteel, 1), new Object[] { "XXX", "XXX", "XXX",
            Character.valueOf('X'), CinderLoE.redDwarfSteel });
        LOTRRecipes.dwarvenRecipes.add(new ShapedOreRecipe(new ItemStack(LOTRMod.banner, 1, 42), new Object[] { " YR", " X ", " Z ",
                Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.wool, Character.valueOf('Z'), "plankWood", Character.valueOf('R'), "dyeRed"}));
        GameRegistry.addRecipe(new LOTRRecipePoisonWeapon(CinderLoE.daggerRedDwarf, CinderLoE.daggerRedDwarfPoisoned));
    }

    public static void registerLimwaithRecipes() {

        OreDictionary.registerOre("bone", Items.bone);
        OreDictionary.registerOre("bone", LOTRMod.elfBone);
        OreDictionary.registerOre("bone", LOTRMod.dwarfBone);
        OreDictionary.registerOre("bone", LOTRMod.hobbitBone);
        OreDictionary.registerOre("bone", LOTRMod.orcBone);
        OreDictionary.registerOre("bone", LOTRMod.trollBone);
        OreDictionary.registerOre("bone", LOTRMod.wargBone);

        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetLimwaith), new Object[] { "XXX", "Y Y",
            Character.valueOf('X'), LOTRMod.driedReeds, Character.valueOf('Y'), new ItemStack(LOTRMod.planks, 1, 15)}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bodyLimwaith), new Object[] { "X X", "YYY", "XXX",
            Character.valueOf('X'), LOTRMod.driedReeds, Character.valueOf('Y'), new ItemStack(LOTRMod.planks, 1, 15)}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.legsLimwaith), new Object[] { "XXX", "Y Y", "X X",
            Character.valueOf('X'), LOTRMod.driedReeds, Character.valueOf('Y'), new ItemStack(LOTRMod.planks, 1, 15)}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bootsLimwaith), new Object[] { "Y Y", "X X",
            Character.valueOf('X'), LOTRMod.driedReeds, Character.valueOf('Y'), new ItemStack(LOTRMod.planks, 1, 15)}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.spearLimwaith), new Object[] { "  X", " Y ", "Y  ",
            Character.valueOf('X'), "bone", Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.truncheonLimwaith), new Object[] { " X ", " X ", " Y ",
            Character.valueOf('X'), "bone", Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.battleaxeLimwaith), new Object[] { "XXX", "XYX", " Y ",
            Character.valueOf('X'), "bone", Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.tridentLimwaith), new Object[] { " XX", " YX", "Y  ",
            Character.valueOf('X'), "bone", Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.daggerLimwaith), new Object[] { "X ", "Y ",
            Character.valueOf('X'), "bone", Character.valueOf('Y'), "stickWood" }));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.blowgunLimwaith), new Object[] { "YXX", "   ", "   ",
            Character.valueOf('X'), LOTRMod.reeds, Character.valueOf('Y'), "stickWood" }));
        GameRegistry.addRecipe(new LOTRRecipePoisonWeapon(CinderLoE.daggerLimwaith, CinderLoE.daggerLimwaithPoisoned));
        LOTRRecipes.moredainRecipes.add(new ShapelessOreRecipe(new ItemStack(CinderLoE.bonemold), new Object[] {"bone", new ItemStack(Items.dye, 1, 15), new ItemStack(Items.dye, 1, 15)}));

        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetboneLimwaith), new Object[] { "XXX", "Y Y",
                Character.valueOf('X'), "bone", Character.valueOf('Y'), CinderLoE.bonemold}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bodyboneLimwaith), new Object[] { "X X", "YYY", "XXX",
                Character.valueOf('X'), "bone", Character.valueOf('Y'), CinderLoE.bonemold}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.legsboneLimwaith), new Object[] { "XXX", "Y Y", "X X",
                Character.valueOf('X'), "bone", Character.valueOf('Y'), CinderLoE.bonemold}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bootsboneLimwaith), new Object[] { "Y Y", "X X",
                Character.valueOf('X'), "bone", Character.valueOf('Y'), CinderLoE.bonemold}));
        LOTRRecipes.moredainRecipes.add(new ShapedOreRecipe(new ItemStack(LOTRMod.banner, 1, 43), new Object[] { " YR", " X ", " Z ",
                Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.wool, Character.valueOf('Z'), "plankWood", Character.valueOf('R'), LOTRMod.reeds}));
    }

    public static void registerBreeRecipes() {
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetBreeKettle), new Object[] { "XYX",
                Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), CinderLoE.helmetBree}));
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetBree), new Object[] { "XXX", "X X",
            Character.valueOf('X'), Items.iron_ingot}));
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bodyBree), new Object[] { "X X", "XXX", "XXX",
            Character.valueOf('X'), Items.iron_ingot }));
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.legsBree), new Object[] { "XXX", "X X", "X X",
            Character.valueOf('X'), Items.iron_ingot }));
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bootsBree), new Object[] { "X X", "X X",
            Character.valueOf('X'), Items.iron_ingot }));
        LOTRRecipes.breeRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.swordBree), new Object[] { " X ", " X ", " Y ",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), "stickWood" }));
    }

    public static void registerArnorRecipes() {
        LOTRRecipes.rangerRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.helmetArnorBanner), new Object[] { "YYY", "Y Y",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.leather }));
        LOTRRecipes.rangerRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bodyArnorBanner), new Object[] { "Y Y", "XXX", "YYY",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.leather }));
        LOTRRecipes.rangerRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.legsArnorBanner), new Object[] { "YYY", "X X", "Y Y",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.leather }));
        LOTRRecipes.rangerRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.bootsArnorBanner), new Object[] { "X X", "X X",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.leather }));
        LOTRRecipes.rangerRecipes.add(new ShapedOreRecipe(new ItemStack(CinderLoE.maceArnor), new Object[] { " XX", " XX", "Y  ",
            Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), "stickWood" }));
    }
}
