package com.zivilon.cinder_loe.client.render;

import lotr.common.entity.LOTRRandomSkinEntity;
import lotr.client.render.entity.LOTRRandomSkins;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderLiving;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

import com.zivilon.cinder_loe.client.model.npc.ModelFangornElk;
import com.zivilon.cinder_loe.entity.npc.radagast.FangornElk;

public class RenderFangornElk extends RenderLiving {
  private static LOTRRandomSkins elkSkins;
  
  private static ResourceLocation saddleTexture = new ResourceLocation("lotr:mob/elk/saddle.png");
  
  public RenderFangornElk() {
    super((ModelBase)new ModelFangornElk(), 0.5F);
    setRenderPassModel((ModelBase)new ModelFangornElk(0.5F));
    elkSkins = LOTRRandomSkins.loadSkinsList("lotr:mob/elk/elk");
  }
  
  public ResourceLocation getEntityTexture(Entity entity) {
    FangornElk elk = (FangornElk)entity;
    ResourceLocation elkSkin = elkSkins.getRandomSkin((LOTRRandomSkinEntity)elk);
    return elkSkin;
  }
}