package com.zivilon.cinder_loe;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.StatCollector;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

public class LoECreativeTabs extends CreativeTabs {
    public static LoECreativeTabs tabBlockLoE = new LoECreativeTabs("tabBlockLoE");
    public static LoECreativeTabs tabCombatLoE = new LoECreativeTabs("tabCombatLoE");
    public static LoECreativeTabs tabSpawnLoE = new LoECreativeTabs("tabSpawnLoE");
    public static LoECreativeTabs tabMiscLoE = new LoECreativeTabs("tabMiscLoE");
    public static LoECreativeTabs tabFoodLoE = new LoECreativeTabs("tabFoodLoE");
    public static LoECreativeTabs tabDecoLoE = new LoECreativeTabs("tabDecoLoE");
    public static LoECreativeTabs tabCharacterLoE = new LoECreativeTabs("tabCharacterLoE");

    public ItemStack theIcon;

    public LoECreativeTabs(String label) {
        super(label);
    }

    public static void setupIcons() {
        tabBlockLoE.theIcon = new ItemStack(CinderLoE.fishBarrel);
        tabCombatLoE.theIcon = new ItemStack(CinderLoE.swordAsh);
        tabSpawnLoE.theIcon = new ItemStack(CinderLoE.spawnEgg);
        tabMiscLoE.theIcon = new ItemStack(CinderLoE.bonemold);
        tabFoodLoE.theIcon = new ItemStack(CinderLoE.onion);
        tabDecoLoE.theIcon = new ItemStack(CinderLoE.goldChain);
        tabCharacterLoE.theIcon = new ItemStack(CinderLoE.sarumanStaff);
    }

    @SideOnly(Side.CLIENT)
    public String getTranslatedTabLabel() {
        return StatCollector.translateToLocal("cinder_loe.creativetab." + getTabLabel());
    }

    @SideOnly(Side.CLIENT)
    public Item getTabIconItem() {
        return this.theIcon.getItem();
    }

    public ItemStack getIconItemStack() {
        return this.theIcon;
    }

}
