package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import lotr.common.LOTRCreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.util.IIcon;

import java.lang.reflect.Field;

public class FishBarrel extends StaticBlockBase3 {

    public FishBarrel() {
        super(Material.wood, "lotr:fishbarrel");
        this.setCreativeTab(LoECreativeTabs.tabDecoLoE);
        setStepSound(Block.soundTypeWood);
        setBlockName("lotr:fishbarrel");
        setHardness(1.0F);
        setResistance(2.0F);
      //  setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabDeco);
    }
}
