package com.zivilon.cinder_loe.items;

import com.zivilon.cinder_loe.LoECreativeTabs;

import cpw.mods.fml.common.network.simpleimpl.IMessage;
import lotr.common.entity.projectile.LOTREntityGandalfFireball;
import lotr.common.network.LOTRPacketHandler;
import lotr.common.network.LOTRPacketWeaponFX;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.EnumAction;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.world.World;

import lotr.common.item.LOTRItemSword;
import lotr.common.item.LOTRStoryItem;

import com.zivilon.cinder_loe.CinderLoE;

public class WizardStaff extends LOTRItemSword implements LOTRStoryItem {
    public WizardStaff() {
        super(CinderLoE.getLOTRMaterialByName("WIZARD"));
        this.setCreativeTab(LoECreativeTabs.tabCharacterLoE);
    }

    public int getMaxItemUseDuration(ItemStack itemstack) {
        return 40;
    }

    public EnumAction getItemUseAction(ItemStack itemstack) {
        return EnumAction.bow;
    }

    public ItemStack onItemRightClick(ItemStack itemstack, World world, EntityPlayer entityplayer) {
        entityplayer.setItemInUse(itemstack, getMaxItemUseDuration(itemstack));
        return itemstack;
    }
}
