package com.zivilon.cinder_loe.client.model;// Made with Blockbench 4.12.4
// Exported for Minecraft version 1.7 - 1.12
// Paste this class into your mod and generate all required imports


import lotr.client.model.LOTRModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDorwinionHelmet extends LOTRModelBiped {
	private final ModelRenderer PlumeItself_r1;
	private final ModelRenderer PlumeFrontBit_r1;
	private final ModelRenderer PlumeTop_r1;

	public ModelDorwinionHelmet(float f) {
		super(f);
		textureWidth = 64;
		textureHeight = 64;

		PlumeItself_r1 = new ModelRenderer(this);
		PlumeItself_r1.setRotationPoint(0.0F, -6.0F, -3.0F);
		setRotationAngle(PlumeItself_r1, -0.2182F, 0.0F, 0.0F);
		PlumeItself_r1.cubeList.add(new ModelBox(PlumeItself_r1, 0, 16, -0.5F, -11.0F, -3.0F, 1, 10, 12, 0.0F));

		PlumeFrontBit_r1 = new ModelRenderer(this);
		PlumeFrontBit_r1.setRotationPoint(0.0F, -10.0F, -5.0F);
		setRotationAngle(PlumeFrontBit_r1, -0.2182F, 0.0F, 0.0F);
		PlumeFrontBit_r1.cubeList.add(new ModelBox(PlumeFrontBit_r1, 32, 6, -1.0F, -1.8F, -0.77F, 2, 1, 1, 0.0F));

		PlumeTop_r1 = new ModelRenderer(this);
		PlumeTop_r1.setRotationPoint(-1.0F, -12.658F, 0.4397F);
		setRotationAngle(PlumeTop_r1, -0.2182F, 0.0F, 0.0F);
		PlumeTop_r1.cubeList.add(new ModelBox(PlumeTop_r1, 26, 16, 0.0F, 1.0F, -5.5F, 2, 1, 11, 0.0F));

		this.bipedHead.cubeList.clear();

		bipedHead = new ModelRenderer(this);
		bipedHead.setRotationPoint(0.0F, 0.0F, 0.0F);
		bipedHead.cubeList.add(new ModelBox(bipedHead, 0, 0, -4.0F, -8.0F, -4.0F, 8, 8, 8, 1.0F));
		bipedHead.cubeList.add(new ModelBox(bipedHead, 36, 49, -5.0F, -3.0F, -4.9F, 10, 7, 0, 0.0F));
		bipedHead.cubeList.add(new ModelBox(bipedHead, 26, 28, -1.0F, -10.0F, -4.5F, 2, 1, 9, 0.0F));
		bipedHead.cubeList.add(new ModelBox(bipedHead, 32, 8, -0.5F, -12.0F, -2.0F, 1, 2, 1, 0.0F));

		bipedHead.addChild(PlumeItself_r1);
		bipedHead.addChild(PlumeFrontBit_r1);
		bipedHead.addChild(PlumeTop_r1);

		this.bipedHeadwear.cubeList.clear();
		this.bipedBody.cubeList.clear();
		this.bipedRightArm.cubeList.clear();
		this.bipedLeftArm.cubeList.clear();
		this.bipedRightLeg.cubeList.clear();
		this.bipedLeftLeg.cubeList.clear();

	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		bipedHead.render(f5);
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}
