package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.blocks.RotatableBlockBase2;
import net.minecraft.block.Block;

import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;

public class IvoryBlock extends RotatableBlockBase2 {
    public IvoryBlock() {
        super(Material.rock, "lotr:ivoryBlock");
        setStepSound(Block.soundTypeStone);
        setBlockName("lotr:ivoryBlock");
        setHardness(1.0F);
        setResistance(5.0F);
    }
}
