package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.LoECreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.creativetab.CreativeTabs;

import lotr.common.LOTRCreativeTabs;

import java.lang.reflect.Field;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

public class BlockRedDwarfSteel extends Block {

    public BlockRedDwarfSteel() {
        super(Material.iron); // Choose the appropriate material
        this.setCreativeTab(LoECreativeTabs.tabBlockLoE);
        setHardness(5.0F);
        setResistance(15.0F);
        setStepSound(Block.soundTypeMetal);
        setBlockTextureName("lotr:red_dwarf_steel");
        setBlockName("lotr:blockRedDwarfSteel");
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:red_dwarf_steel");
    }
}
