package com.zivilon.cinder_loe.entity.npc;

import com.zivilon.cinder_loe.CinderLoE;
import lotr.common.entity.npc.LOTRBannerBearer;
import lotr.common.entity.npc.LOTREntityHobbitBounder;
import lotr.common.item.LOTRItemBanner;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MovingObjectPosition;
import net.minecraft.world.World;

public class HobbitBannerBearer extends LOTREntityHobbitBounder implements LOTRBannerBearer {
    public HobbitBannerBearer(World world) {
        super(world);
    }
    @Override
    public LOTRItemBanner.BannerType getBannerType() {
        return LOTRItemBanner.BannerType.HOBBIT;
    }
    @Override
    public ItemStack getPickedResult(MovingObjectPosition target) {
        return new ItemStack(CinderLoE.spawnEgg, 1, 16);
    }

    @Override
    public void attackEntityWithRangedAttack(EntityLivingBase p_82196_1_, float p_82196_2_) {

    }
}
