package com.zivilon.cinder_loe.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * cavalry_spikes - Cleric_red
 * Created using Tabula 4.1.1
 */
public class barricade_post extends ModelBase {
    public ModelRenderer shape1;
    public ModelRenderer shape1_1;

    public barricade_post() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.shape1_1 = new ModelRenderer(this, 0, 0);
        this.shape1_1.setRotationPoint(-3.0F, 9.0F, 4.0F);
        this.shape1_1.addBox(1.0F, 0.0F, 2.0F, 4, 18, 4, 0.0F);
        this.setRotateAngle(shape1_1, -0.6981317007977318F, 0.0F, 0.0F);
        this.shape1 = new ModelRenderer(this, 0, 0);
        this.shape1.setRotationPoint(-3.0F, 13.0F, -8.5F);
        this.shape1.addBox(1.0F, 0.0F, 0.0F, 4, 18, 4, 0.0F);
        this.setRotateAngle(shape1, 0.6981317007977318F, 0.0F, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        this.shape1_1.render(f5);
        this.shape1.render(f5);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
