package com.zivilon.cinder_loe.entity.corrupt;

import com.zivilon.cinder_loe.CinderLoE_Config;
import lotr.common.LOTRAchievement;
import lotr.common.LOTRFoods;
import lotr.common.LOTRMod;
import lotr.common.entity.ai.LOTREntityAIAttackOnCollide;
import lotr.common.entity.npc.LOTREntityDwarf;
import lotr.common.entity.npc.LOTREntityHobbit;
import lotr.common.entity.npc.LOTREntityHobbitBounder;
import lotr.common.entity.npc.LOTRNames;
import lotr.common.fac.LOTRFaction;
import lotr.common.item.LOTRItemLeatherHat;
import lotr.common.world.structure.LOTRChestContents;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.IEntityLivingData;
import net.minecraft.entity.ai.EntityAIBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MovingObjectPosition;
import net.minecraft.world.World;

public class CorruptHobbit extends LOTREntityHobbitBounder {
    private LOTRFaction faction;
    public CorruptHobbit(World world) {
        super(world);
        this.spawnRidingHorse = false;
    }
    @Override
    public ItemStack getPickedResult(MovingObjectPosition target) {
        return null;
    }
    @Override
    public IEntityLivingData onSpawnWithEgg(IEntityLivingData data) {
        return null;
    }
    @Override
    protected LOTRFoods getHobbitFoods() {
        return LOTRFoods.ORC;
    }
    @Override
    protected LOTRFoods getHobbitDrinks() {
        return LOTRFoods.ORC_DRINK;
    }
    @Override
    public float getAlignmentBonus() {
        return 0.0f;
    }

    @Override
    public boolean getCanSpawnHere() {
        return false;
    }

    @Override
    public float getBlockPathWeight(int i, int j, int k) {
        float f = 0.0f;
        return f;
    }
    @Override
    public LOTRFaction getFaction() {
        return LOTRFaction.valueOf(CinderLoE_Config.corrupt_faction);
    }
    @Override
    protected float getSoundPitch() {
        return super.getSoundPitch() * 1.5f;
    }
    @Override
    public String getHurtSound() {
        return "lotr:orc.hurt";
    }
    @Override
    public String getDeathSound() {
        return "lotr:orc.death";
    }

    @Override
    public String getAttackSound() {
        return "lotr:orc.attack";
    }

    @Override
    public String getSpeechBank(EntityPlayer entityplayer) {
        if (this.isFriendlyAndAligned(entityplayer)) {
            return "corruptSpeak/all/neutral";
        }
        return "corruptSpeak/all/hostile";
    }
    @Override
    protected void dropFewItems(boolean flag, int i) {
    }

    protected void dropHobbitItems(boolean flag, int i) {
        super.dropHobbitItems(flag, i);
    }

}
