package com.zivilon.cinder_loe.items;

import com.zivilon.cinder_loe.CinderLoE;
import com.zivilon.cinder_loe.LoECreativeTabs;
import cpw.mods.fml.common.network.simpleimpl.IMessage;
import lotr.common.LOTRLevelData;
import lotr.common.LOTRMod;
import lotr.common.fac.LOTRFaction;
import lotr.common.item.LOTRItemBow;
import lotr.common.item.LOTRMaterial;
import lotr.common.network.LOTRPacketHandler;
import lotr.common.network.LOTRPacketWeaponFX;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraft.potion.PotionEffect;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.World;
import org.spongepowered.asm.mixin.Overwrite;

import java.util.List;

public class CinderBow extends LOTRItemBow {
    public Item repair_item;

    public CinderBow(LOTRMaterial material, double d, Item item) {
        super(material, d);
        setCreativeTab(LoECreativeTabs.tabCombatLoE);
        repair_item = item;
    }

    @Override
    public boolean getIsRepairable(ItemStack item, ItemStack repair_material) {
        if (repair_material.getItem() == repair_item)
            return true;
        return false;
    }


}
