package com.zivilon.cinder_loe.items;

import lotr.common.item.LOTRMaterial;
import lotr.common.item.LOTRItemArmor;
import com.zivilon.cinder_loe.LoECreativeTabs;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class LoEArmor extends LOTRItemArmor {
    public Item repair_item;

    public LoEArmor(LOTRMaterial material, int slotType) {
        this(material, slotType, "");
    }
    public LoEArmor(LOTRMaterial material, int slotType, String s) {
        this(material, slotType, s, (Item) null);
    }
    public LoEArmor(LOTRMaterial material, int slotType, Item item) {
        this(material, slotType, "", item);
    }
    public LoEArmor(LOTRMaterial material, int slotType, Block block) {
        this(material, slotType, "", block);
    }
    public LoEArmor(LOTRMaterial material, int slotType, String s, Block block) {
        this(material, slotType, s, Item.getItemFromBlock(block));
    }
    public LoEArmor(LOTRMaterial material, int slotType, String s, Item item) {
        super(material, slotType, s);
        repair_item = item;
        setCreativeTab(LoECreativeTabs.tabCombatLoE);
    }

    @Override
    public boolean getIsRepairable(ItemStack item, ItemStack repair_material) {
        if (repair_material.getItem() == repair_item)
            return true;
        return false;
    }
}
