package com.zivilon.cinder_loe.blocks;

import com.zivilon.cinder_loe.util.Utilities;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import com.zivilon.cinder_loe.LoECreativeTabs;

import java.lang.reflect.Field;

public class plaster extends Block {

    public plaster() {
        super(Material.rock); // Choose the appropriate material
        setCreativeTab(LoECreativeTabs.tabBlockLoE);
        // Set other properties like hardness, resistance, name, etc.
        setHardness(2.0F);
        setResistance(5.0F);
        setBlockTextureName(Utilities.toSnakeCase("lotr:plaster"));
        setBlockName("lotr:plaster");
      //  setCreativeTab((CreativeTabs) LOTRCreativeTabs.tabBlock);
    }

    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister iconRegister) {
        this.blockIcon = iconRegister.registerIcon("lotr:plaster");
    }

}
