package com.zivilon.cinder_loe.items;

import com.zivilon.cinder_loe.LoECreativeTabs;
import lotr.common.item.LOTRItemDagger;
import lotr.common.item.LOTRMaterial;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class LoEDagger extends LOTRItemDagger {
    public Item repair_item;

    public LoEDagger(LOTRMaterial material, DaggerEffect poison, Item redDwarfSteel) {
        this(material, (Item) null);
    }
    public LoEDagger(LOTRMaterial material, Block repair_block) {
        this(material, Item.getItemFromBlock(repair_block));
    }
    public LoEDagger(LOTRMaterial material, Item item) {
        super(material);
        repair_item = item;
        setCreativeTab(LoECreativeTabs.tabCombatLoE);
    }

    @Override
    public boolean getIsRepairable(ItemStack item, ItemStack repair_material) {
        if (repair_material.getItem() == repair_item)
            return true;
        return false;
    }
}
