package com.zivilon.cinder_loe.entity.corrupt;

import com.zivilon.cinder_loe.CinderLoE_Config;
import lotr.common.LOTRFoods;
import lotr.common.LOTRMod;
import lotr.common.entity.ai.LOTREntityAIAttackOnCollide;
import lotr.common.entity.npc.LOTREntityDwarf;
import lotr.common.entity.npc.LOTREntityElf;
import lotr.common.entity.npc.LOTRNames;
import lotr.common.fac.LOTRFaction;
import lotr.common.item.LOTRItemMug;
import lotr.common.world.structure.LOTRChestContents;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.IEntityLivingData;
import net.minecraft.entity.SharedMonsterAttributes;
import net.minecraft.entity.ai.EntityAIBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MovingObjectPosition;
import net.minecraft.world.World;
import net.minecraftforge.common.config.Configuration;

import static com.zivilon.cinder_loe.CinderLoE_Config.config;

public class CorruptDwarf extends LOTREntityDwarf {

    @Override
    public ItemStack getPickedResult(MovingObjectPosition target) {
        return null;
    }
    public CorruptDwarf(World world) {
        super(world);
    }
    @Override
    public void setupNPCGender() {
        this.familyInfo.setMale(true);
    }
    @Override
    public void setupNPCName() {
        this.familyInfo.setName(LOTRNames.getDwarfName(this.rand, this.familyInfo.isMale()));
    }
    @Override
    public IEntityLivingData onSpawnWithEgg(IEntityLivingData data) {
        return null;
    }
    @Override
    public LOTRFaction getFaction() {
        return LOTRFaction.valueOf(CinderLoE_Config.corrupt_faction);
    }

    @Override
    protected float getSoundPitch() {
        return super.getSoundPitch() * 0.65f;
    }
    @Override
    public String getSpeechBank(EntityPlayer entityplayer) {
        if (this.isFriendlyAndAligned(entityplayer)) {
            return "corruptSpeak/all/neutral";
        }
        return "corruptSpeak/all/hostile";
    }
    @Override
    protected void dropFewItems(boolean flag, int i) {
        super.dropFewItems(flag, i);
    }
}
