package com.zivilon.cinder_loe.client.model;
// Made with Blockbench 4.11.1
// Exported for Minecraft version 1.7 - 1.12
// Paste this class into your mod and generate all required imports


import lotr.client.model.LOTRModelBiped;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGalvornHelmet extends LOTRModelBiped {
	private final ModelRenderer crest;
	private final ModelRenderer shape12;
	private final ModelRenderer shape3;
	private final ModelRenderer shape4;
	private final ModelRenderer shape5;
	private final ModelRenderer shape6;

	public ModelGalvornHelmet(float f) {
		super(f);
		this.textureWidth = 64;
		this.textureHeight = 32;

		crest = new ModelRenderer(this);
		crest.setRotationPoint(0.0F, -1.0F, 0.55F);

		shape12 = new ModelRenderer(this);
		shape12.setRotationPoint(0.5F, -4.0F, -6.35F);
		setRotationAngle(shape12, 1.5708F, 0.0F, 0.0F);
		shape12.cubeList.add(new ModelBox(shape12, 43, 22, -1.0F, 0.0F, -1.5F, 1, 1, 9, 0.0F));

		shape3 = new ModelRenderer(this);
		shape3.setRotationPoint(0.0F, 0.0F, 0.0F);
		setRotationAngle(shape3, 0.0F, -0.2276F, 0.0F);
		shape3.cubeList.add(new ModelBox(shape3, 0, 25, -1.0F, 0.1F, 0.0F, 1, 0, 6, 0.0F));

		shape4 = new ModelRenderer(this);
		shape4.setRotationPoint(0.0F, 0.0F, 0.0F);
		setRotationAngle(shape4, 0.0F, -0.2731F, 0.0F);
		shape4.cubeList.add(new ModelBox(shape4, 16, 23, -1.0F, 0.2F, 0.0F, 1, 0, 5, 0.0F));

		shape5 = new ModelRenderer(this);
		shape5.setRotationPoint(-1.0F, 0.0F, 0.0F);
		setRotationAngle(shape5, 0.0F, 0.2276F, 0.0F);
		shape5.cubeList.add(new ModelBox(shape5, 50, 3, 0.0F, 0.1F, 0.0F, 1, 0, 6, 0.0F));

		shape6 = new ModelRenderer(this);
		shape6.setRotationPoint(0.0F, 0.0F, 0.0F);

		setRotationAngle(shape6, 0.0F, 0.2731F, 0.0F);
		shape6.cubeList.add(new ModelBox(shape6, 49, 13, 0.0F, 0.2F, 0.0F, 1, 0, 5, 0.0F));

		this.bipedHead.cubeList.clear();

		bipedHead = new ModelRenderer(this);
		bipedHead.setRotationPoint(0.0F, 0.0F, 0.0F);
		bipedHead.cubeList.add(new ModelBox(bipedHead, 0, 0, -4.0F, -8.0F, -4.0F, 8, 8, 8, 1.0F));

//		this.crest.addChild(this.shape12);
//		this.crest.addChild(this.shape3);
//		this.crest.addChild(this.shape4);
//		this.crest.addChild(this.shape5);
//		this.crest.addChild(this.shape6);
		crest.addChild(shape12);
		shape12.addChild(shape3);
		shape3.addChild(shape4);
		shape12.addChild(shape5);
		shape5.addChild(shape6);
		this.bipedHead.addChild(this.crest);

		this.bipedHeadwear.cubeList.clear();
		this.bipedBody.cubeList.clear();
		this.bipedRightArm.cubeList.clear();
		this.bipedLeftArm.cubeList.clear();
		this.bipedRightLeg.cubeList.clear();
		this.bipedLeftLeg.cubeList.clear();

	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		bipedHead.render(f5);
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}